-- +goose Up
-- +goose StatementBegin
CREATE TABLE language_levels (
                                 id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                 language_level_name varchar(10) NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE language_levels;
-- +goose StatementEnd
